### ISSUE TITLE
About the training code

### ISSUE THREAD

**Issue by liujianzhao6328057** [yn-sun/ea-cnn#1]
Hi,yanan.Thanks for your excellent jobs . Could you please upload a copy of training  code since i am not familiar with the training procedure of the evolutionary algorithms.

**Comment by yn-sun** [comment]
Hi Jianzhao,

Which training code you would like to have? the training code for the whole algorithm, or the training code for each generated network?

Cheers,
Yanan

**Comment by 1810325** [comment]
would you like Upload them all ?the training code for each generated network,and the whole algorithm ,Thank you again for your work

**Comment by 1810325** [comment]
@yn-sun would you like Upload them all ?the training code for each generated network,and the whole algorithm ,Thank you again for your work

**Comment by yn-sun** [comment]
> @yn-sun would you like Upload them all ?the training code for each generated network,and the whole algorithm ,Thank you again for your work

Hi, the training code has been already there. You could find it from template/cifar10.py
Thanks.

**Comment by 1810325** [comment]
Oh, I'm newer,sorry~Where can I find the trained model

**Comment by 1810325** [comment]
Thanks for your response~ Why do I run CIFAR10 without error  but show no result

**Comment by 1810325** [comment]
@yn-sun your '/home/yanan/train_data'Can I see it, please

**Comment by 1810325** [comment]
@yn-sun 作者您好,请问我该怎么做才能用我自己的数据集加上您给出的方法,训练一个网络出来呢,因为我是新手,真诚的需要您的帮助

**Comment by 1810325** [comment]
@yn-sun 你能提供一个更加完整的代码吗

**Comment by 1810325** [comment]
@liujianzhao6328057 Have you successfully run this code? I have no results when I run cifar. I want to know what I should do.

**Comment by 1810325** [comment]
@yn-sun cifar10.py只定义了几个函数啊,什么都没调用,运行也没有结果啊

**Comment by yn-sun** [comment]
> @yn-sun cifar10.py只定义了几个函数啊,什么都没调用,运行也没有结果啊
一看就是你没看懂这个代码怎么运行的。我建议你 不要乱发这种信息了 收到了你好几封类似邮件了 就想着直接替换到你的问题中。我们不会回答你任何关于你的 “如何让这个代码使用我的数据集”。
