### ISSUE TITLE
With regard to the cifar10.py issue

### ISSUE THREAD

**Issue by yuxiaomu** [yn-sun/ea-cnn#2]
do I need to write the main function in cifar10.py to implement this model

**Comment by yn-sun** [comment]
> do I need to write the main function in cifar10.py to implement this model

If you would like to run your own dataset, you need to rewrite the cifar10.py.

**Comment by yuxiaomu** [comment]
i just want to run the cifar ,not my own dataset,what should i do

**Comment by yn-sun** [comment]
> i just want to run the cifar ,not my own dataset,what should i do

Please run rhe evolve.py script. Some changes may need to be made that is based on your cofiguration

**Comment by yuxiaomu** [comment]
thanks for your reply,i will check it now,thank you very much....

At 2019-11-20 15:44:35, "yn-sun" <notifications@github.com> wrote:


i just want to run the cifar ,not my own dataset,what should i do

Please run rhe evolve.py script. Some changes may need to be made that is based on your cofiguration

**Comment by yn-sun** [comment]
> thanks for your reply,i will check it now,thank you very much.... At 2019-11-20 15:44:35, "yn-sun" <notifications@github.com> wrote: i just want to run the cifar ,not my own dataset,what should i do Please run rhe evolve.py script. Some changes may need to be made that is based on your cofiguration — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You are welcome. Please let me know if some changes have been made because this file was made on my own compute platform, not sure how many changes would be made when other people are using it.

**Comment by yuxiaomu** [comment]
Not yet, because I have just come into contact. By the way, isn't evalue.py just an evaluation function

**Comment by yn-sun** [comment]
> Not yet, because I have just come into contact. By the way, isn't evalue.py just an evaluation function

It is the entry file of the whole algorithm.
